import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  container: { 
    flex: 1,
    backgroundColor: '#c6ddf4ff',
    
    // paddingHorizontal: 5,
  },

  
  profileImage: {
  width: 38,
  height: 38,
  borderRadius: 19,
  borderWidth: 2,
  borderColor: '#fff',
  marginLeft: 8,
},


  banner: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'linear-gradient(90deg, #e63946 0%, #e94880 100%)',
     backgroundColor: '#e63946',
    paddingTop: 38,
    paddingBottom: 16,
    paddingHorizontal: 21,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  bannerTitle: { color: '#fff', fontWeight: 'bold', fontSize: 18, flex: 1 },
  bannerSubtitle: { color: '#fff', fontSize: 10, marginLeft: 10, opacity: 0.8 },
  bannerIcon: { marginRight: 10 },

  greetingBox: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 16,
    marginHorizontal: 11,
    marginTop: 15,
    elevation: 2,
    shadowColor: '#AAA',
    shadowOpacity: 0.1,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 4,
  },
  greetingText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1D3557',
    marginBottom: 4,
  },
  greetingSubText: {
    fontSize: 14,
    color: '#457B9D',
  },

  infoBox: {
    backgroundColor: '#fff',
    borderRadius: 16,
    padding: 15,
    marginTop:15,
    marginHorizontal: 11,
    marginBottom: 17,
    elevation: 3,
    shadowColor: '#AAA',
    shadowOpacity: 0.11,
    shadowOffset: { width: 0, height: 2 },
    shadowRadius: 6,
  },
  infoTitle: { fontWeight: 'bold', color: '#1D3557', fontSize: 13, marginBottom: 2 },
  infoAddress: { fontWeight: '600', color: '#1D3557', fontSize: 15 },
  infoGps: { color: '#00a896', fontSize: 12, marginTop: 4 },
  infoAutoShare: { color: '#4361ee', backgroundColor: '#f1f2fc', fontSize: 12, marginTop: 7, borderRadius: 6, paddingHorizontal: 7, paddingVertical: 4, opacity: 0.91 },
  viewButton: {
  backgroundColor: '#19af60', // Solid green, matches your emergency active bar
  borderRadius: 8,
  paddingVertical: 7,
  paddingHorizontal: 15,
  marginLeft: 4,
  marginTop: 2,
  alignSelf: 'flex-start',
},
viewButtonText: {
  color: '#fff',
  fontWeight: '600',
  fontSize: 13,
},
  sosButton: {
    backgroundColor: '#e63946',
    borderRadius: 18,
    paddingVertical: 36,
    alignItems: 'center',
    marginHorizontal:18,
    marginTop: 10,
    marginBottom: 18,
    elevation: 4,
    shadowColor: '#e63946',
    shadowOpacity: 0.22,
    shadowOffset: { width: 0, height: 5 },
    shadowRadius: 18,
    justifyContent: 'center',
    height:300,
  },
  sosText: { fontSize: 26, letterSpacing: 1, fontWeight: 'bold', color: '#fff' },
  sosSubText: { fontSize: 13, color: '#fff', marginTop: 8 },

  sectionTitle: {
    fontWeight: '600',
    fontSize: 15,
    paddingTop: 12,
    paddingBottom: 5,
    color: '#1D3557',
    marginLeft: 3,
  },

  // Emergency Level Cards
  severityContainer:{
    marginHorizontal:18
  },
  severityBoxRed: {
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#fa4545',
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  severityBoxOrange: {
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#ffb022',
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  severityBoxYellow: {
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#d0c52dff',
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  severityBoxGreen: {
    backgroundColor: '#fff',
    borderWidth: 1.5,
    borderColor: '#79d02dff',
    borderRadius: 14,
    padding: 12,
    marginBottom: 12,
    elevation: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  severityTitle: { fontWeight: 'bold', fontSize: 15, color: '#1d3557', flex: 1 },
  severityBadge: {
    backgroundColor: '#E63946',
    color: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 7,
    fontWeight: 'bold',
    fontSize: 12,
    marginLeft: 8,
  },
  severityBadgeOrange: {
    backgroundColor: '#F4A259',
    color: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 7,
    fontWeight: 'bold',
    fontSize: 12,
    marginLeft: 8,
  },
  severityBadgeBlue: {
    backgroundColor: '#457B9D',
    color: '#fff',
    paddingHorizontal: 10,
    paddingVertical: 2,
    borderRadius: 7,
    fontWeight: 'bold',
    fontSize: 12,
    marginLeft: 8,
  },
  severityText: { color: '#888', fontSize: 12, flex: 2, marginLeft: 6 },
  hotlineCard: {
    backgroundColor: '#ebf4fb',
    borderRadius: 10,
    paddingVertical: 13,
    alignItems: 'center',
    marginVertical: 13,
    borderColor: '#457B9D',
    borderWidth: 1,
  },
  hotline: { 
    color: '#1D3557', 
    fontWeight: 'bold', 
    fontSize: 15, 
  marginHorizontal:18},
  tipRedOutline: {
    borderWidth: 2,
    borderColor: "#e74c3c",
    borderRadius: 15,
    backgroundColor: "#fff1f0",
    padding: 15,
    margin: 12,
    marginTop: 22,
  },
  tipTitleRed: {
    fontWeight: "700",
    fontSize: 15.6,
    color: "#ce244a",
    marginBottom: 6,
  },
  tipOrangeOutline: {
    borderWidth: 2,
    borderColor: "#f4a15d",
    borderRadius: 15,
    backgroundColor: "#fff6f0",
    padding: 15,
    margin: 12,
    marginTop: 17,
  },
  tipTitleOrange: {
    fontWeight: "700",
    fontSize: 15.6,
    color: "#e67e22",
    marginBottom: 6,
  },
  tipStep: {
    fontSize: 13.4,
    marginBottom: 2.5,
    color: "#63392a",
  },
  tipStrong: {
    fontWeight: "700",
    color: "#111",
  },
  cprBtnRed: {
    marginTop: 13,
    backgroundColor: "#e01a1a",
    borderRadius: 10,
    alignItems: "center",
    paddingVertical: 11,
  },
  cprBtnRedText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
    letterSpacing: 0.25,
  },
  
  logoutButton: {
    backgroundColor: "#2362e3",
    borderRadius: 20,
    margin: 18,
    marginTop: 5,
    padding: 16,
    alignItems: "center",
    position: "relative",
    bottom: 0,
  },
  logoutButtonText: { 
    color: '#F1FAEE',
    fontSize: 17, 
    fontWeight: '600'
   },
});

export default styles;
