import { StyleSheet } from "react-native";

export default StyleSheet.create({
  rootContainer: {
    flex: 1,
    backgroundColor: "#f6f6f6",
  },
  headerBar: {
    backgroundColor: "#3066fe",
    paddingTop: 38,
    paddingBottom: 16,
    paddingHorizontal: 21,
    borderBottomLeftRadius: 18,
    borderBottomRightRadius: 18,
  },
  headerTitle: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 22,
    marginBottom: 3,
  },
  headerSubtitle: {
    color: "#deebff",
    fontSize: 14.5,
    fontWeight: "400",
  },
  scrollContent: {
    paddingVertical: 16,
    paddingBottom: 28,
  },
  card: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
    marginHorizontal: 13,
    marginVertical: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.055,
    elevation: 3,
  },
  cardTitle: {
    fontSize: 15.5,
    fontWeight: "600",
    color: "#464646",
    marginBottom: 7,
  },
  chipRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginBottom: 9,
  },
  chip: {
    backgroundColor: "#fdeac9",
    paddingHorizontal: 13,
    paddingVertical: 7,
    marginRight: 7,
    marginBottom: 6,
    borderRadius: 19,
    flexDirection: "row",
    alignItems: "center",
  },
  chipDanger: {
    backgroundColor: "#fcd6d9",
    paddingHorizontal: 13,
    paddingVertical: 7,
    marginRight: 7,
    marginBottom: 6,
    borderRadius: 19,
    flexDirection: "row",
    alignItems: "center",
  },
  chipText: {
    fontWeight: "500",
    color: "#2d1818",
    marginRight: 3,
    fontSize: 14.2,
  },
  chipInputRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 3,
  },
  chipInput: {
    flex: 1,
    borderRadius: 19,
    paddingHorizontal: 15,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: "#ece0cc",
    fontSize: 15,
    backgroundColor: "#f6f2ea",
    marginRight: 5,
    color: "#3b2a13"
  },
  chipAddBtn: {
    backgroundColor: "#f7bb64",
    borderRadius: 19,
    padding: 7,
  },
  chipAddBtnDanger: {
    backgroundColor: "#db617a",
    borderRadius: 19,
    padding: 7,
  },
  input: {
    backgroundColor: "#eff0f7",
    borderRadius: 9,
    padding: 11,
    marginBottom: 8,
    fontSize: 15,
    borderWidth: 1,
    borderColor: "#e3e3e3"
  },
  medItemContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#f4f4ff",
    borderRadius: 8,
    padding: 10,
    marginVertical: 4,
  },
  medItem: {
    fontSize: 14.3,
    color: "#222",
    flex: 1,
  },
  // Medical Documents
  uploadBox: {
    borderWidth: 1.5,
    borderStyle: "dashed",
    borderColor: "#62a7e6",
    borderRadius: 11,
    padding: 18,
    alignItems: "center",
    marginVertical: 10,
    backgroundColor: "#fafdff",
  },
  uploadText: {
    marginTop: 3,
    fontWeight: "600",
    color: "#3560a2",
    fontSize: 14.6,
  },
  uploadSubText: {
    fontSize: 12.7,
    color: "#7890a2",
    textAlign: "center",
    marginTop: 2,
  },
  fileRow: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#f9fbff",
    borderRadius: 8,
    paddingVertical: 10,
    paddingHorizontal: 11,
    marginTop: 7,
    marginBottom: 2,
    borderWidth: 1,
    borderColor: "#dbe7fa"
  },
  fileTitle: {
    fontSize: 14.2,
    fontWeight: "600",
    color: "#25327a",
  },
  fileDate: {
    fontSize: 11,
    color: "#8da4c9",
  },
  viewBtn: {
    color: "#2d67fd",
    fontWeight: "700",
    paddingLeft: 11,
    fontSize: 14,
  },
  // CPR and Emergency Cards
  tipRedOutline: {
    borderWidth: 2,
    borderColor: "#e74c3c",
    borderRadius: 15,
    backgroundColor: "#fff1f0",
    padding: 15,
    margin: 12,
    marginTop: 22,
  },
  tipTitleRed: {
    fontWeight: "700",
    fontSize: 15.6,
    color: "#ce244a",
    marginBottom: 6,
  },
  tipOrangeOutline: {
    borderWidth: 2,
    borderColor: "#f4a15d",
    borderRadius: 15,
    backgroundColor: "#fff6f0",
    padding: 15,
    margin: 12,
    marginTop: 17,
  },
  tipTitleOrange: {
    fontWeight: "700",
    fontSize: 15.6,
    color: "#e67e22",
    marginBottom: 6,
  },
  tipStep: {
    fontSize: 13.4,
    marginBottom: 2.5,
    color: "#63392a",
  },
  tipStrong: {
    fontWeight: "700",
    color: "#111",
  },
  cprBtnRed: {
    marginTop: 13,
    backgroundColor: "#e01a1a",
    borderRadius: 10,
    alignItems: "center",
    paddingVertical: 11,
  },
  cprBtnRedText: {
    color: "#fff",
    fontWeight: "800",
    fontSize: 15,
    letterSpacing: 0.25,
  },
  saveBtnBottom: {
    backgroundColor: "#2362e3",
    borderRadius: 20,
    margin: 18,
    marginTop: 5,
    padding: 16,
    alignItems: "center",
    position: "relative",
    bottom: 0,
  },
  saveBtnText: {
    color: "#fff",
    fontWeight: "700",
    fontSize: 17,
  },
});
